version: "3.8"
services:
  mysql:
    image: mysql:8
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  lobo-liquibase:
    container_name: lobo-liquibase
    restart: on-failure
    env_file: ./.env
    depends_on:
      - mysql
    image: kilna/liquibase-mysql
    command: liquibase --url=jdbc:mysql://mysql:$MYSQLDB_DOCKER_PORT/userapi_db?useSSL=false --driver=com.mysql.jdbc.Driver --username=root --password=password --changeLogFile=/workspace/changelog.xml update
    volumes:
      - ./src/main/resources/changelog.xml:/workspace/changelog.xml
      - ./src/main/resources/data:/workspace/data
  userapi-main:
    restart: on-failure
    env_file: ./.env
    depends_on:
      - lobo-liquibase
    container_name: userapi-server
    build:
        context: .
        dockerfile: Dockerfile
    image: userapi-server:latest
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysql:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "none"
      }'
volumes:
  db: